name: Cart

on:
  push:
    branches:
      - master
    # paths:
    #   - '**.js'
    #   - '.github/workflows/cart.yaml'

  pull_request:
    branches:
      - master
    paths:
      - '**.js'
      - '.github/workflows/cart.yaml'

jobs:
  payment:
    name: Build and deploy cart microservice
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker image
        run: |
          cd cart/
          docker build -t cart .

      - name: Docker Login (use secrets)
        run: docker login sharnithacr.azurecr.io -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Push
        run: |
          docker tag cart sharnithacr/robot-shop:${{ github.run_id }}
          docker push sharnithacr/robot-shop:${{ github.run_id }}
